"use client";

import { useState } from "react";
import {
    createBrand,
    addCompetitor,
    addPrompt,
    listPrompts,
    type Brand,
    type TrackedPrompt,
} from "@/lib/api";

type Step = "brand" | "competitors" | "prompts" | "review";

export default function SetupPage() {
    const [step, setStep] = useState<Step>("brand");
    const [error, setError] = useState("");
    const [loading, setLoading] = useState(false);

    // Brand data
    const [brandName, setBrandName] = useState("");
    const [domain, setDomain] = useState("");
    const [industry, setIndustry] = useState("");
    const [createdBrand, setCreatedBrand] = useState<Brand | null>(null);

    // Competitors
    const [competitors, setCompetitors] = useState<{ name: string; domain: string }[]>([]);
    const [compName, setCompName] = useState("");
    const [compDomain, setCompDomain] = useState("");

    // Prompts (auto-generated by backend, user can add/remove)
    const [generatedPrompts, setGeneratedPrompts] = useState<TrackedPrompt[]>([]);
    const [extraPrompts, setExtraPrompts] = useState<{ text: string; language: string; region: string }[]>([]);
    const [promptText, setPromptText] = useState("");
    const [promptsLoading, setPromptsLoading] = useState(false);

    function addComp() {
        if (!compName.trim()) return;
        setCompetitors((prev) => [...prev, { name: compName.trim(), domain: compDomain.trim() }]);
        setCompName("");
        setCompDomain("");
    }

    function removeComp(idx: number) {
        setCompetitors((prev) => prev.filter((_, i) => i !== idx));
    }

    function addExtraPrompt() {
        if (!promptText.trim()) return;
        setExtraPrompts((prev) => [...prev, { text: promptText.trim(), language: "en", region: "IN" }]);
        setPromptText("");
    }

    function removeExtraPrompt(idx: number) {
        setExtraPrompts((prev) => prev.filter((_, i) => i !== idx));
    }

    async function handleCreateBrand() {
        setError("");
        setLoading(true);
        try {
            const brand = await createBrand({
                name: brandName,
                domain: domain || undefined,
                industry: industry || undefined,
            });
            setCreatedBrand(brand);

            // Load the auto-generated prompts
            setPromptsLoading(true);
            try {
                const prompts = await listPrompts(brand.id);
                setGeneratedPrompts(prompts);
            } catch {
                // Still continue even if loading fails
            } finally {
                setPromptsLoading(false);
            }

            setStep("competitors");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to create brand");
        } finally {
            setLoading(false);
        }
    }

    async function handleFinish() {
        if (!createdBrand) return;
        setError("");
        setLoading(true);
        try {
            // Create competitors
            for (const c of competitors) {
                await addCompetitor(createdBrand.id, {
                    name: c.name,
                    domain: c.domain || undefined,
                });
            }
            // Create any extra prompts the user added manually
            for (const p of extraPrompts) {
                await addPrompt(createdBrand.id, p);
            }
            window.location.href = "/dashboard";
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to save setup");
        } finally {
            setLoading(false);
        }
    }

    const totalPrompts = generatedPrompts.length + extraPrompts.length;

    return (
        <div
            style={{
                minHeight: "100vh",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                background: "var(--background)",
                padding: "2rem",
            }}
        >
            <div
                style={{
                    width: "100%",
                    maxWidth: 600,
                    background: "var(--card)",
                    border: "1px solid var(--border)",
                    borderRadius: 12,
                    padding: "2.5rem 2rem",
                }}
            >
                {/* Progress indicator */}
                <div style={{ display: "flex", gap: "0.5rem", marginBottom: "2rem" }}>
                    {(["brand", "competitors", "prompts", "review"] as Step[]).map((s, i) => (
                        <div
                            key={s}
                            style={{
                                flex: 1,
                                height: 4,
                                borderRadius: 2,
                                background:
                                    (["brand", "competitors", "prompts", "review"] as Step[]).indexOf(step) >= i
                                        ? "var(--primary)"
                                        : "var(--border)",
                            }}
                        />
                    ))}
                </div>

                {error && (
                    <div
                        style={{
                            background: "#fef2f2",
                            color: "#b91c1c",
                            padding: "0.75rem 1rem",
                            borderRadius: 8,
                            fontSize: "0.875rem",
                            marginBottom: "1rem",
                        }}
                    >
                        {error}
                    </div>
                )}

                {/* Step 1: Brand */}
                {step === "brand" && (
                    <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                        <h2 style={{ fontSize: "1.25rem", fontWeight: 700, margin: 0 }}>
                            Set up your brand
                        </h2>
                        <p style={{ color: "var(--muted-foreground)", fontSize: "0.9rem", margin: 0 }}>
                            Tell us about the brand you want to track across AI engines.
                        </p>

                        <label style={labelStyle}>
                            Brand Name *
                            <input
                                type="text"
                                required
                                value={brandName}
                                onChange={(e) => setBrandName(e.target.value)}
                                placeholder="e.g. Zerodha"
                                style={inputStyle}
                            />
                        </label>

                        <label style={labelStyle}>
                            Website Domain
                            <input
                                type="text"
                                value={domain}
                                onChange={(e) => setDomain(e.target.value)}
                                placeholder="e.g. zerodha.com"
                                style={inputStyle}
                            />
                        </label>

                        <label style={labelStyle}>
                            Industry
                            <input
                                type="text"
                                value={industry}
                                onChange={(e) => setIndustry(e.target.value)}
                                placeholder="e.g. Fintech, SaaS, E-commerce"
                                style={inputStyle}
                            />
                        </label>

                        <button
                            onClick={handleCreateBrand}
                            disabled={!brandName.trim() || loading}
                            style={btnPrimary(loading)}
                        >
                            {loading ? "Creating…" : "Next → Competitors"}
                        </button>
                    </div>
                )}

                {/* Step 2: Competitors */}
                {step === "competitors" && (
                    <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                        <h2 style={{ fontSize: "1.25rem", fontWeight: 700, margin: 0 }}>
                            Add competitors
                        </h2>
                        <p style={{ color: "var(--muted-foreground)", fontSize: "0.9rem", margin: 0 }}>
                            We&apos;ll compare your brand&apos;s AI visibility against these competitors.
                        </p>

                        <div style={{ display: "flex", gap: "0.5rem" }}>
                            <input
                                type="text"
                                value={compName}
                                onChange={(e) => setCompName(e.target.value)}
                                placeholder="Competitor name"
                                style={{ ...inputStyle, flex: 1 }}
                                onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addComp())}
                            />
                            <input
                                type="text"
                                value={compDomain}
                                onChange={(e) => setCompDomain(e.target.value)}
                                placeholder="domain.com"
                                style={{ ...inputStyle, flex: 1 }}
                                onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addComp())}
                            />
                            <button onClick={addComp} style={btnSecondary}>
                                Add
                            </button>
                        </div>

                        {competitors.length > 0 && (
                            <div style={{ display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                                {competitors.map((c, i) => (
                                    <div
                                        key={i}
                                        style={{
                                            display: "flex",
                                            justifyContent: "space-between",
                                            alignItems: "center",
                                            padding: "0.5rem 0.75rem",
                                            background: "var(--background)",
                                            borderRadius: 6,
                                            fontSize: "0.875rem",
                                        }}
                                    >
                                        <span>
                                            {c.name}
                                            {c.domain && (
                                                <span style={{ color: "var(--muted-foreground)", marginLeft: 8 }}>
                                                    {c.domain}
                                                </span>
                                            )}
                                        </span>
                                        <button
                                            onClick={() => removeComp(i)}
                                            style={{ background: "none", border: "none", cursor: "pointer", color: "#b91c1c" }}
                                        >
                                            ✕
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}

                        <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.5rem" }}>
                            <button onClick={() => setStep("brand")} style={btnSecondary}>
                                ← Back
                            </button>
                            <button onClick={() => setStep("prompts")} style={btnPrimary(false)}>
                                Next → Prompts
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 3: Prompts (auto-generated, user can review/add) */}
                {step === "prompts" && (
                    <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                        <h2 style={{ fontSize: "1.25rem", fontWeight: 700, margin: 0 }}>
                            Review tracked prompts
                        </h2>
                        <p style={{ color: "var(--muted-foreground)", fontSize: "0.9rem", margin: 0 }}>
                            We auto-generated these queries based on your brand and industry. They&apos;ll be asked to AI engines daily. You can add more below.
                        </p>

                        {/* Auto-generated prompts */}
                        {promptsLoading ? (
                            <p style={{ color: "var(--muted-foreground)", fontSize: "0.875rem" }}>Generating prompts…</p>
                        ) : generatedPrompts.length > 0 ? (
                            <div>
                                <p style={{ fontSize: "0.8rem", color: "var(--muted-foreground)", margin: "0 0 0.5rem", fontWeight: 600 }}>
                                    Auto-generated ({generatedPrompts.length})
                                </p>
                                <div style={{ display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                                    {generatedPrompts.map((p) => (
                                        <div
                                            key={p.id}
                                            style={{
                                                padding: "0.5rem 0.75rem",
                                                background: "var(--background)",
                                                borderRadius: 6,
                                                fontSize: "0.875rem",
                                                borderLeft: "3px solid var(--primary)",
                                            }}
                                        >
                                            {p.text}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ) : (
                            <p style={{ color: "var(--muted-foreground)", fontSize: "0.875rem" }}>
                                No prompts were auto-generated. Add some manually below.
                            </p>
                        )}

                        {/* Manual add */}
                        <div>
                            <p style={{ fontSize: "0.8rem", color: "var(--muted-foreground)", margin: "0 0 0.5rem", fontWeight: 600 }}>
                                Add custom prompts (optional)
                            </p>
                            <div style={{ display: "flex", gap: "0.5rem" }}>
                                <input
                                    type="text"
                                    value={promptText}
                                    onChange={(e) => setPromptText(e.target.value)}
                                    placeholder="e.g. What is the best fintech app in India?"
                                    style={{ ...inputStyle, flex: 1 }}
                                    onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addExtraPrompt())}
                                />
                                <button onClick={addExtraPrompt} style={btnSecondary}>
                                    Add
                                </button>
                            </div>
                        </div>

                        {extraPrompts.length > 0 && (
                            <div style={{ display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                                {extraPrompts.map((p, i) => (
                                    <div
                                        key={i}
                                        style={{
                                            display: "flex",
                                            justifyContent: "space-between",
                                            alignItems: "center",
                                            padding: "0.5rem 0.75rem",
                                            background: "var(--background)",
                                            borderRadius: 6,
                                            fontSize: "0.875rem",
                                        }}
                                    >
                                        <span>{p.text}</span>
                                        <button
                                            onClick={() => removeExtraPrompt(i)}
                                            style={{ background: "none", border: "none", cursor: "pointer", color: "#b91c1c" }}
                                        >
                                            ✕
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}

                        <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.5rem" }}>
                            <button onClick={() => setStep("competitors")} style={btnSecondary}>
                                ← Back
                            </button>
                            <button onClick={() => setStep("review")} style={btnPrimary(false)}>
                                Next → Review
                            </button>
                        </div>
                    </div>
                )}

                {/* Step 4: Review */}
                {step === "review" && (
                    <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                        <h2 style={{ fontSize: "1.25rem", fontWeight: 700, margin: 0 }}>
                            Review your setup
                        </h2>

                        <div style={sectionStyle}>
                            <h3 style={sectionTitle}>Brand</h3>
                            <p style={{ margin: 0 }}>
                                <strong>{brandName}</strong>
                                {domain && <span style={{ color: "var(--muted-foreground)" }}> — {domain}</span>}
                                {industry && <span style={{ color: "var(--muted-foreground)" }}> ({industry})</span>}
                            </p>
                        </div>

                        <div style={sectionStyle}>
                            <h3 style={sectionTitle}>
                                Competitors ({competitors.length})
                            </h3>
                            {competitors.length === 0 ? (
                                <p style={{ color: "var(--muted-foreground)", margin: 0, fontSize: "0.875rem" }}>
                                    None added — you can add them later in Settings.
                                </p>
                            ) : (
                                <ul style={{ margin: 0, paddingLeft: "1.25rem", fontSize: "0.875rem" }}>
                                    {competitors.map((c, i) => (
                                        <li key={i}>
                                            {c.name}
                                            {c.domain && ` (${c.domain})`}
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </div>

                        <div style={sectionStyle}>
                            <h3 style={sectionTitle}>
                                Tracked Prompts ({totalPrompts})
                            </h3>
                            {totalPrompts === 0 ? (
                                <p style={{ color: "var(--muted-foreground)", margin: 0, fontSize: "0.875rem" }}>
                                    None generated — you can add them later in Settings.
                                </p>
                            ) : (
                                <ul style={{ margin: 0, paddingLeft: "1.25rem", fontSize: "0.875rem" }}>
                                    {generatedPrompts.map((p) => (
                                        <li key={p.id}>{p.text}</li>
                                    ))}
                                    {extraPrompts.map((p, i) => (
                                        <li key={`extra-${i}`}>{p.text}</li>
                                    ))}
                                </ul>
                            )}
                        </div>

                        <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.5rem" }}>
                            <button onClick={() => setStep("prompts")} style={btnSecondary}>
                                ← Back
                            </button>
                            <button
                                onClick={handleFinish}
                                disabled={loading}
                                style={btnPrimary(loading)}
                            >
                                {loading ? "Saving…" : "Complete Setup →"}
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

const labelStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "var(--foreground)",
};

const inputStyle: React.CSSProperties = {
    padding: "0.65rem 0.75rem",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--background)",
    color: "var(--foreground)",
    fontSize: "0.9rem",
};

function btnPrimary(loading: boolean): React.CSSProperties {
    return {
        flex: 1,
        padding: "0.75rem",
        borderRadius: 8,
        border: "none",
        background: "var(--primary)",
        color: "#fff",
        fontSize: "0.95rem",
        fontWeight: 600,
        cursor: loading ? "wait" : "pointer",
        opacity: loading ? 0.7 : 1,
    };
}

const btnSecondary: React.CSSProperties = {
    padding: "0.65rem 1rem",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--background)",
    color: "var(--foreground)",
    fontSize: "0.9rem",
    cursor: "pointer",
};

const sectionStyle: React.CSSProperties = {
    padding: "1rem",
    background: "var(--background)",
    borderRadius: 8,
};

const sectionTitle: React.CSSProperties = {
    fontSize: "0.9rem",
    fontWeight: 600,
    marginTop: 0,
    marginBottom: "0.5rem",
};
