"""add_intent_to_tracked_prompts

Revision ID: 377eadef8bbe
Revises: ad0e117da845
Create Date: 2026-04-12 14:21:42.512133
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '377eadef8bbe'
down_revision: Union[str, None] = 'ad0e117da845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_prompts', sa.Column('intent', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_prompts', 'intent')
    # ### end Alembic commands ###
