"""initial

Revision ID: ad0e117da845
Revises: 
Create Date: 2026-03-30 10:02:35.148965
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad0e117da845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_ts', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('monthly_prompt_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brands_org_name', 'brands', ['organization_id', 'name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('crawler_type', sa.Enum('GPTBOT', 'CLAUDEBOT', 'GOOGLEBOT', 'BINGBOT', 'PERPLEXITYBOT', 'METABOT', 'BYTESPIDER', 'UNKNOWN', name='crawlertype'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('request_path', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawler_brand_type_ts', 'crawler_logs', ['brand_id', 'crawler_type', 'timestamp'], unique=False)
    op.create_table('tracked_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_brand_active', 'tracked_prompts', ['brand_id', 'is_active'], unique=False)
    op.create_table('visibility_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.Enum('CHATGPT', 'PERPLEXITY', 'GEMINI', 'GOOGLE_AIO', 'CLAUDE', 'COPILOT', 'GROK', 'DEEPSEEK', 'META_AI', 'SARVAM', 'KRUTRIM', name='aiengine'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('share_of_model', sa.Float(), nullable=False),
    sa.Column('avg_generative_position', sa.Float(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('total_prompts_run', sa.Integer(), nullable=False),
    sa.Column('positive_sentiment_pct', sa.Float(), nullable=False),
    sa.Column('negative_sentiment_pct', sa.Float(), nullable=False),
    sa.Column('neutral_sentiment_pct', sa.Float(), nullable=False),
    sa.Column('top_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visibility_brand_engine_date', 'visibility_scores', ['brand_id', 'engine', 'date'], unique=True)
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.Enum('CHATGPT', 'PERPLEXITY', 'GEMINI', 'GOOGLE_AIO', 'CLAUDE', 'COPILOT', 'GROK', 'DEEPSEEK', 'META_AI', 'SARVAM', 'KRUTRIM', name='aiengine'), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('generative_position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment'), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['tracked_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responses_captured_at', 'ai_responses', ['captured_at'], unique=False)
    op.create_index('ix_responses_prompt_engine', 'ai_responses', ['prompt_id', 'engine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responses_prompt_engine', table_name='ai_responses')
    op.drop_index('ix_responses_captured_at', table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index('ix_visibility_brand_engine_date', table_name='visibility_scores')
    op.drop_table('visibility_scores')
    op.drop_index('ix_prompts_brand_active', table_name='tracked_prompts')
    op.drop_table('tracked_prompts')
    op.drop_index('ix_crawler_brand_type_ts', table_name='crawler_logs')
    op.drop_table('crawler_logs')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_brands_org_name', table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_audit_ts', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
